version: '3'

services:
  # Container for programming & development.
  dev:
    build: ./dev/
    volumes:
      - /P_DRIVE/docker/services/data:/data
      - /U_DRIVE:/union
      - /var/opt/svn:/var/opt/svn
    ports:
      - 7777:7777
    tty: true
    stdin_open: true

  # Portainer for managing Docker
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/opt/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  # SVN
  svn:
    build: ./svn/
    restart: always
    ports:
      - 3690:3690
    volumes:
      - /U_DRIVE/Common/Database/svn/vault:/var/opt/svn

  # Database containers
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/opt/postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
